apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qyah
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qyah
    app.kubernetes.io/part-of: tkwch-fix-0075-0073-app
  name: devfile-sample-qyah
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qyah
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qyah
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0073-tenant/tkwch-fix-0075-0073-app/devfile-sample-qyah@sha256:c68d38be6ad1ea36935f0a7676b01413693079c6284edf517ee32f74b91a0aae
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
